[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "discord>=2.3.2",
    "google-genai>=1.11.0",
    "google-generativeai>=0.8.5",
    "python-dotenv>=1.1.0",
]
